artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/entbappy/Branching-tutorial/raw/master/Chicken-fecal-images.zip
  kaggle_dataset:  ismailpromus/skin-diseases-image-dataset
  local_data_file: artifacts/data_ingestion/raw/skin conditions.zip
  unzip_dir: artifacts/data_ingestion/processed/extracted_data

prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5